[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyssp"
version = "0.0.1"
readme = "README.md"

[tool.pytest.ini_options]
pythonpath = "."
addopts = [
    "--import-mode=importlib",
]
