"""Chapter 5 algorithm implementations."""

import numpy as np


def rtoa(r) -> tuple[np.ndarray, np.ndarray]: ...
def gtoa(gamma): ...
def atog(a): ...
def gtor(gamma, epsilon=None): ...
def ator(a, b): ...
def rtog(r): ...
def glev(r, b): ...
