"""Chapter 4 modeling algorithm implementations."""

from numpy import ndarray

def pade(x, p, q): ...
def prony(x, p, q): ...
def shanks(x, p, q): ...
def spike(g, n0, n): ...
def ipf(): ...
def acm(x, p) -> tuple[ndarray, ndarray]: ...
def covm(x, p): ...
def durbin(x, p, q): ...
