"""Power spectrum and Frequency Estimators."""


def periodogram(x, n1=0, n2=None, nfft=1024): ...
def mper(x, n1, n2, win=None): ...
def bart(x, nsect): ...
def welch(x, L, over, win=None): ...
def per_smooth(x, M, n1=0, n2=None, win=None): ...
def minvar(x, p): ...
def mem(x, p): ...
def phd(x, p): ...
def music(x, p, M): ...
def ev(x, p, M): ...
def min_norm(x, p, M): ...
def bt_pc(x, p, M): ...

def overlay():
    raise NotImplementedError()
def modal(x, p, q):
    raise NotImplementedError()
def mv_pc(x, p, M):
    raise NotImplementedError()
def ar_pc(x, p, M):
    raise NotImplementedError()
