name: Python Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r developer/requirements-testing.txt

      - name: Static Lint
        run: |
          ruff . --verbose --output-format=github

      - name: Static Type Check
        run: |
          mypy --verbose

      - name: Test
        run: |
          pytest --verbose
