name: Python Continuous Integration

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
                cache: 'pip'

            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip setuptools wheel
                pip install -r requirements.txt

    analyze:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Lint
              run: |
                python --version

            - name: Mypy Typecheck
              run: |
                python --version

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Pytest tests
              run: |
                python -m pytest
